### ISSUE TITLE
Есть вопрос по сотрудничеству

### ISSUE THREAD

**Issue by AlexWolker** [ruprotaf/MDB-UART-converter-from-Atmega644p--Arduino-mega-etc-#2]
Доброго дня.
занимаюсь поиском специалиста, кто смог бы подружить ардуино и картридер, может будет вам интересно? или подскажете к кому можно обратиться? большая часть кода как вижу у вас уже есть....

**Comment by ruprotaf** [comment]
Пиши в телегу @FedorProtasov - попробую помочь.
